from context.shared.domain.exception.error_base import ErrorBase


class BadRequestErrorBase(ErrorBase):
    pass
